// The icon a list page shows beside a heading: a sector or publication in the first column, a part in the second.
// Headings are DBIE's own names, so the icon is chosen by what the name says, the first rule that matches winning;
// the rules run from the specific (a publication's subject, a part's cadence) to the broad (a sector), and anything
// none of them names gets the table mark. All icons are Lucide's.

// UI ==================================================================================================================
import {
    Archive,
    ArrowLeftRight,
    Banknote,
    BookOpen,
    Briefcase,
    Building,
    Building2,
    Calendar,
    CalendarClock,
    CalendarDays,
    CalendarRange,
    ChartCandlestick,
    ChartLine,
    ChartPie,
    ClipboardList,
    Clock,
    Coins,
    Factory,
    FileSpreadsheet,
    FileText,
    Flag,
    Gauge,
    Globe,
    HandCoins,
    Landmark,
    Map,
    MapPin,
    Newspaper,
    Percent,
    PiggyBank,
    Plane,
    Receipt,
    Scale,
    Ship,
    Smartphone,
    Sprout,
    Star,
    Table2,
    Tag,
    TrendingUp,
    Users,
    Vault,
    Wallet,
    Wheat,
    type LucideIcon,
} from "lucide-react";

const RULES : [ RegExp, LucideIcon ][] = [
    // Publications, by subject
    [ /bsr\)?-?\s*1\b|outstanding credit|on credit/i,                  HandCoins ],
    [ /bsr\)?-?\s*2\b|bsr2|deposits? with|\(deposit\)/i,               PiggyBank ],
    [ /spatial distribution|statistics on deposits and credit/i,        Map ],
    [ /bank branch/i,                                                   MapPin ],
    [ /international banking/i,                                         Globe ],
    [ /handbook/i,                                                      BookOpen ],
    [ /bulletin/i,                                                      Newspaper ],
    [ /co-operative banks/i,                                            Building ],
    [ /internal debt/i,                                                 FileText ],
    [ /public debt/i,                                                   Receipt ],
    [ /statistical tables relating to banks/i,                          Table2 ],
    [ /weekly statistical supplement/i,                                 CalendarDays ],

    // Parts of a publication
    [ /discontinued|old .*classification/i,                             Archive ],
    [ /growth rates and ratios/i,                                       Percent ],
    [ /less than monthly/i,                                             CalendarClock ],
    [ /time series|^charts$/i,                                          ChartLine ],
    [ /annual accounts/i,                                               FileSpreadsheet ],
    [ /data tables|other tables/i,                                      Table2 ],
    [ /occasional/i,                                                    Star ],
    [ /reserve bank of india/i,                                         Building2 ],
    [ /payment/i,                                                       Smartphone ],
    [ /government accounts|treasury bills/i,                            Scale ],
    [ /prices and production|prices & wages|prices/i,                   Tag ],
    [ /money and banking|monetary/i,                                    Banknote ],

    // Cadences
    [ /\bdaily\b/i,                                                     Clock ],
    [ /\bquarterly\b|\bmonthly\b/i,                                     CalendarRange ],
    [ /\bannual\b/i,                                                    Calendar ],

    // Statistics sections
    [ /non banking financial compan|nbfc/i,                             Wallet ],
    [ /fdi/i,                                                           Plane ],
    [ /listed/i,                                                        ChartCandlestick ],
    [ /financial and investment compan/i,                               Coins ],
    [ /private limited/i,                                               Building ],
    [ /public limited|compan/i,                                         Building2 ],
    [ /external debt/i,                                                 Receipt ],
    [ /indices/i,                                                       Percent ],
    [ /forex reserve/i,                                                 Vault ],
    [ /international finance/i,                                         Banknote ],
    [ /international trade|trade/i,                                     Ship ],
    [ /equity|corporate debt/i,                                         ChartCandlestick ],
    [ /forex market/i,                                                  ArrowLeftRight ],
    [ /government securities/i,                                         FileText ],
    [ /money market/i,                                                  Coins ],
    [ /assets & liabilities|assets and liabilities/i,                   Landmark ],
    [ /performance/i,                                                   Gauge ],
    [ /sectoral/i,                                                      ChartPie ],
    [ /financial institutions/i,                                        Building ],
    [ /key rates/i,                                                     Percent ],
    [ /combined/i,                                                      Scale ],
    [ /central govt/i,                                                  Flag ],
    [ /state govt/i,                                                    Map ],
    [ /agricultur/i,                                                    Wheat ],
    [ /industrial/i,                                                    Factory ],
    [ /national income/i,                                               TrendingUp ],
    [ /socio-economic/i,                                                Users ],
    [ /survey/i,                                                        ClipboardList ],

    // Statistics sectors
    [ /corporate sector/i,                                              Briefcase ],
    [ /external sector/i,                                               Globe ],
    [ /financial markets?/i,                                            ChartCandlestick ],
    [ /financial sector/i,                                              Landmark ],
    [ /public finance/i,                                                Scale ],
    [ /real sector/i,                                                   Sprout ],
];

export const headingIcon = (label : string) : LucideIcon => RULES.find(([ test ]) => test.test(label))?.[1] ?? Table2;
